language: rust
sudo: false
cache: cargo
rust: nightly
os:
- linux
- osx
install:
- rustup target add wasm32-unknown-unknown
script:
- cargo web build --target=wasm32-unknown-unknown --verbose
- cargo web build --target=wasm32-unknown-unknown --all-features --verbose
- cargo test --verbose
