[package]
name = "screeps-game-api"
version = "0.9.0"
authors = ["David Ross <daboross@daboross.net>"]
documentation = "https://docs.rs/screeps-game-api/"
edition = "2018"
include = [
    "Cargo.toml",
    "Web.toml",
    "src/**/*",
    "tests/**/*",
    "examples/**/*",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rustyscreeps/screeps-game-api/"
description = "WASM bindings to the in-game Screeps API"

[lib]
name = "screeps"

[badges]
travis-ci = { repository = "rustyscreeps/screeps-game-api" }

[dependencies]
arrayvec = "0.4"
enum-iterator = "0.3"
js-sys = "0.3"
num-derive = "0.2"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[features]
check-all-casts = []
