[package]
name = "screeps-game-api"
version = "0.9.0"
authors = ["David Ross <daboross@daboross.net>"]
documentation = "https://docs.rs/screeps-game-api/"
edition = "2018"
include = [
    "Cargo.toml",
    "Web.toml",
    "src/**/*",
    "tests/**/*",
    "examples/**/*",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rustyscreeps/screeps-game-api/"
description = "WASM bindings to the in-game Screeps API"

[lib]
name = "screeps"

[badges]
travis-ci = { repository = "rustyscreeps/screeps-game-api" }

[dependencies]
arrayvec = "0.5"
enum_dispatch = "0.3"
enum-iterator = "0.6"
js-sys = "0.3"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[features]
# Disable the interface for pixel generation, not present on private servers
disable-generate-pixel = []

# Disable the interface for inter-shard memory, not present on private servers
disable-inter-shard-memory = []

# Disable inter-player market transactions - used in season 1
disable-market = []

# Disable terminal structures - proposed but not used in season 1
disable-terminal = []

# Enable score structures and resource - used in season 1
enable-score = []

# Disable interfaces that don't exist (and will panic if used) on private servers
private-server = ["disable-inter-shard-memory", "disable-generate-pixel"]

# Seasonal server, season 1; market removed, score structures and resource added
seasonal-season-1 = ["disable-market", "enable-score"]
